---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: CI

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  # push:
  #   branches-ignore: [master, main]
  #   # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  test:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false

# name: CI
# on: [pull_request]
# jobs:
#   test:
#     name: runner / eslint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - uses: reviewdog/action-eslint@v1
#         with:
#           reporter: github-pr-check
#           eslint_flags: 'pages/'
# name: CI

# on: [pull_request, pull_request_target]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 14
#       - name: Install
#         run: npm ci  # OR: yarn 
#       - name: Run eslint on changed files
#         uses: tj-actions/eslint-changed-files@v8
#         with:
#           # config_path: "/path/to/.eslintrc"
#           # ignore_path: "/path/to/.eslintignore"
#           # extensions: "ts,tsx,js,jsx"
#           # extra_args: "--max-warnings=0"
#           token: ${{ secrets.TOKEN }}
#           config_path: ".eslintrc.json"
#           ignore_path: ""
#           extensions: "ts,tsx,js,jsx"
#           extra_args: "--max-warnings=0"
